export { default as Similar } from './Similar'
export { default as Crew } from './Crew'
export { default as Featured } from './Featured'
export { default as Information } from './Information'
export { default as Providers } from './Providers'

export { default as GetYear } from './GetYear'
export { default as GetGenre } from './GetGenre'
export { default as GetCountry } from './GetCountry'
export { default as GetRuntime } from './GetRuntime'
export { default as GetCompanies } from './GetCompanies'
export { default as RatingStars } from './RatingStars'